// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvFZJ9dInr4viz91qva9n2N8LCcfo2PQ',
    appId: '1:226903346204:web:9f9568e95f8935c2aba3d9',
    messagingSenderId: '226903346204',
    projectId: 'bleattendance-ce0b9',
    authDomain: 'bleattendance-ce0b9.firebaseapp.com',
    storageBucket: 'bleattendance-ce0b9.firebasestorage.app',
    measurementId: 'G-8WPENEW0N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCb3TMCk5jqP7Q6RgT9HdWQYxClT9sbU',
    appId: '1:226903346204:android:5bc127223b927ae1aba3d9',
    messagingSenderId: '226903346204',
    projectId: 'bleattendance-ce0b9',
    storageBucket: 'bleattendance-ce0b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pWq2amRqLwSItzV9ipN323xmRTVEjys',
    appId: '1:226903346204:ios:6cdb0b22fa0d36d8aba3d9',
    messagingSenderId: '226903346204',
    projectId: 'bleattendance-ce0b9',
    storageBucket: 'bleattendance-ce0b9.firebasestorage.app',
    iosBundleId: 'com.example.bleScannerLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0pWq2amRqLwSItzV9ipN323xmRTVEjys',
    appId: '1:226903346204:ios:6cdb0b22fa0d36d8aba3d9',
    messagingSenderId: '226903346204',
    projectId: 'bleattendance-ce0b9',
    storageBucket: 'bleattendance-ce0b9.firebasestorage.app',
    iosBundleId: 'com.example.bleScannerLogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGvFZJ9dInr4viz91qva9n2N8LCcfo2PQ',
    appId: '1:226903346204:web:be692b2b3d72ba87aba3d9',
    messagingSenderId: '226903346204',
    projectId: 'bleattendance-ce0b9',
    authDomain: 'bleattendance-ce0b9.firebaseapp.com',
    storageBucket: 'bleattendance-ce0b9.firebasestorage.app',
    measurementId: 'G-E7YHWNCJ5V',
  );
}
